package edu.century.finalProject;

public interface PHB extends Constants{
	
	/* Dragonborn Races - Player's Handbook
	 * Subraces = Colors
	 */
	
	public final Race dragonbornBlack = new Race(DRAGONBORN_NAME, "Black", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_BLACK, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornBlue = new Race(DRAGONBORN_NAME, "Blue", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_BLUE, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornBrass = new Race(DRAGONBORN_NAME, "Brass", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_BRASS, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornBronze = new Race(DRAGONBORN_NAME, "Bronze", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_BRONZE, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE,DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornCopper = new Race(DRAGONBORN_NAME, "Copper", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_COPPER, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornGold = new Race(DRAGONBORN_NAME, "Gold", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_GOLD, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornGreen = new Race(DRAGONBORN_NAME, "Green", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_GREEN, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornRed = new Race(DRAGONBORN_NAME, "Red", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_RED, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornSilver = new Race(DRAGONBORN_NAME, "Silver", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_SILVER, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);
	
	public final Race dragonbornWhite = new Race(DRAGONBORN_NAME, "White", DRAGONBORN_RACIALBONUS, DRAGONBORN_SUBRACEBONUS, 
			DRAGONBORN_RESISTANCES_WHITE, DRAGONBORN_LANGUAGES, DRAGONBORN_SPEED, DRAGONBORN_DARKVISION, DRAGONBORN_FEATURE, DRAGONBORN_SUBRACE_FEATURE);

	
	/* Dwarf Races - Player's Handbook
	 * Subraces: Hill, Mountain
	 */
	
	public final Race dwarfHill = new Race(DWARF_NAME, DWARF_NAME_HILL, DWARF_RACIALBONUS, DWARF_SUBRACEBONUS_HILL, DWARF_RESISTANCES, DWARF_LANGUAGES,
			DWARF_SPEED, DWARF_DARKVISION, DWARF_FEATURES, DWARF_FEATURES_HILL);
	public final Race dwarfMountain = new Race(DWARF_NAME, DWARF_NAME_MOUNTAIN, DWARF_RACIALBONUS, DWARF_SUBRACEBONUS_MOUNTAIN, DWARF_RESISTANCES, DWARF_LANGUAGES,
			DWARF_SPEED, DWARF_DARKVISION, DWARF_FEATURES, DWARF_FEATURES_MOUNTAIN);
}
